-- Code generated by foundation traffic; DO NOT EDIT.
-- traffic-schema-version: 1
-- traffic-schema-digest: cbc1a64e2fc14316fa6c85a245e43cd68403ec4e52907b4808f8d3b7633babef

DROP TABLE IF EXISTS traffic_baselines;
DROP TABLE IF EXISTS traffic_visitor_markers;
DROP TABLE IF EXISTS traffic_daily;
DROP TABLE IF EXISTS traffic_totals;
DROP TABLE IF EXISTS traffic_event_receipts;
DROP TABLE IF EXISTS traffic_instances;

