-- Code generated by foundation traffic; DO NOT EDIT.
-- traffic-schema-version: 1
-- traffic-schema-digest: cbc1a64e2fc14316fa6c85a245e43cd68403ec4e52907b4808f8d3b7633babef

CREATE TABLE traffic_instances (
    instance_key TEXT PRIMARY KEY,
    schema_version INTEGER NOT NULL CHECK (schema_version = 1),
    catalog_version BIGINT NOT NULL CHECK (catalog_version > 0),
    catalog_digest TEXT NOT NULL,
    time_zone TEXT NOT NULL,
    visitor_secret BYTEA NOT NULL CHECK (octet_length(visitor_secret) = 32),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE traffic_event_receipts (
    instance_key TEXT NOT NULL REFERENCES traffic_instances(instance_key) ON DELETE CASCADE,
    event_id TEXT NOT NULL,
    fingerprint BYTEA NOT NULL CHECK (octet_length(fingerprint) = 32),
    resource_kind TEXT NOT NULL,
    resource_id TEXT NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    metric_day DATE NOT NULL,
    visit_class TEXT NOT NULL CHECK (visit_class IN ('unknown', 'human', 'bot', 'internal')),
    visitor_token BYTEA CHECK (visitor_token IS NULL OR octet_length(visitor_token) = 32),
    counted BOOLEAN NOT NULL,
    drop_reason TEXT NOT NULL DEFAULT '',
    first_instance_visitor BOOLEAN NOT NULL DEFAULT FALSE,
    first_resource_visitor BOOLEAN NOT NULL DEFAULT FALSE,
    received_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (instance_key, event_id),
    CHECK (counted OR drop_reason <> ''),
    CHECK (visitor_token IS NOT NULL OR (NOT first_instance_visitor AND NOT first_resource_visitor))
);

CREATE TABLE traffic_totals (
    instance_key TEXT NOT NULL REFERENCES traffic_instances(instance_key) ON DELETE CASCADE,
    scope_kind TEXT NOT NULL CHECK (scope_kind IN ('instance', 'resource')),
    resource_kind TEXT NOT NULL DEFAULT '',
    resource_id TEXT NOT NULL DEFAULT '',
    views BIGINT NOT NULL DEFAULT 0 CHECK (views >= 0),
    unique_visitor_days BIGINT NOT NULL DEFAULT 0 CHECK (unique_visitor_days >= 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (instance_key, scope_kind, resource_kind, resource_id),
    CHECK (
        (scope_kind = 'instance' AND resource_kind = '' AND resource_id = '')
        OR (scope_kind = 'resource' AND resource_kind <> '' AND resource_id <> '')
    )
);

CREATE TABLE traffic_daily (
    instance_key TEXT NOT NULL REFERENCES traffic_instances(instance_key) ON DELETE CASCADE,
    metric_day DATE NOT NULL,
    scope_kind TEXT NOT NULL CHECK (scope_kind IN ('instance', 'resource')),
    resource_kind TEXT NOT NULL DEFAULT '',
    resource_id TEXT NOT NULL DEFAULT '',
    views BIGINT NOT NULL DEFAULT 0 CHECK (views >= 0),
    unique_visitor_days BIGINT NOT NULL DEFAULT 0 CHECK (unique_visitor_days >= 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (instance_key, metric_day, scope_kind, resource_kind, resource_id),
    CHECK (
        (scope_kind = 'instance' AND resource_kind = '' AND resource_id = '')
        OR (scope_kind = 'resource' AND resource_kind <> '' AND resource_id <> '')
    )
);

CREATE TABLE traffic_visitor_markers (
    instance_key TEXT NOT NULL REFERENCES traffic_instances(instance_key) ON DELETE CASCADE,
    metric_day DATE NOT NULL,
    scope_kind TEXT NOT NULL CHECK (scope_kind IN ('instance', 'resource')),
    resource_kind TEXT NOT NULL DEFAULT '',
    resource_id TEXT NOT NULL DEFAULT '',
    visitor_token BYTEA NOT NULL CHECK (octet_length(visitor_token) = 32),
    first_seen_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (
        instance_key, metric_day, scope_kind, resource_kind, resource_id, visitor_token
    ),
    CHECK (
        (scope_kind = 'instance' AND resource_kind = '' AND resource_id = '')
        OR (scope_kind = 'resource' AND resource_kind <> '' AND resource_id <> '')
    )
);

CREATE TABLE traffic_baselines (
    instance_key TEXT NOT NULL REFERENCES traffic_instances(instance_key) ON DELETE CASCADE,
    source TEXT NOT NULL,
    resource_kind TEXT NOT NULL,
    resource_id TEXT NOT NULL,
    fingerprint BYTEA NOT NULL CHECK (octet_length(fingerprint) = 32),
    views BIGINT NOT NULL CHECK (views >= 0),
    imported_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (instance_key, source, resource_kind, resource_id)
);

CREATE INDEX traffic_event_receipts_received_idx
    ON traffic_event_receipts (instance_key, received_at);

CREATE INDEX traffic_event_receipts_resource_idx
    ON traffic_event_receipts (instance_key, resource_kind, resource_id);

CREATE INDEX traffic_totals_top_views_idx
    ON traffic_totals (instance_key, resource_kind, views DESC, resource_id)
    WHERE scope_kind = 'resource';

CREATE INDEX traffic_totals_top_unique_idx
    ON traffic_totals (instance_key, resource_kind, unique_visitor_days DESC, resource_id)
    WHERE scope_kind = 'resource';

CREATE INDEX traffic_daily_scope_range_idx
    ON traffic_daily (
        instance_key, scope_kind, resource_kind, resource_id, metric_day
    );

CREATE INDEX traffic_daily_kind_range_idx
    ON traffic_daily (instance_key, resource_kind, metric_day)
    WHERE scope_kind = 'resource';

CREATE INDEX traffic_visitor_markers_retention_idx
    ON traffic_visitor_markers (instance_key, metric_day);

CREATE INDEX traffic_visitor_markers_resource_idx
    ON traffic_visitor_markers (instance_key, resource_kind, resource_id)
    WHERE scope_kind = 'resource';

CREATE INDEX traffic_baselines_resource_idx
    ON traffic_baselines (instance_key, resource_kind, resource_id);

