-- Code generated by foundation urllifecycle; DO NOT EDIT.
-- urllifecycle-schema-version: 1
-- urllifecycle-schema-digest: 2cef701acb11295ec8a6ea85c8ef8570fd4a2616214f5bfb73c7907a8930b1a8

DROP TABLE IF EXISTS url_lifecycle_history;
DROP TABLE IF EXISTS url_lifecycle_commands;
DROP TABLE IF EXISTS url_lifecycle_overlays;
DROP TABLE IF EXISTS url_lifecycle_references;
DROP TABLE IF EXISTS url_lifecycle_routes;
DROP TABLE IF EXISTS url_lifecycle_instances;
