-- Code generated by foundation siteprofile; DO NOT EDIT.
-- siteprofile-schema-version: 1
-- siteprofile-schema-digest: 936cf8fcf35942ea126f97e71cae576c58fd6997b36db22ed737fad0dcda1aae

DROP TABLE IF EXISTS site_profile_state;
