-- Code generated by foundation siteprofile; DO NOT EDIT.
-- siteprofile-schema-version: 1
-- siteprofile-schema-digest: 936cf8fcf35942ea126f97e71cae576c58fd6997b36db22ed737fad0dcda1aae

CREATE TABLE site_profile_state (
    id              SMALLINT PRIMARY KEY DEFAULT 1,
    revision        BIGINT NOT NULL,
    schema_version  BIGINT NOT NULL,
    document        JSONB NOT NULL,
    document_digest TEXT NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL,
    CONSTRAINT site_profile_state_singleton CHECK (id = 1),
    CONSTRAINT site_profile_state_revision CHECK (revision > 0),
    CONSTRAINT site_profile_state_schema_version CHECK (schema_version > 0),
    CONSTRAINT site_profile_state_digest CHECK (document_digest ~ '^[0-9a-f]{64}$')
);
