-- Code generated by foundation authorization; DO NOT EDIT.
-- authorization-schema-version: 1
-- authorization-schema-digest: 6159bde6b6d615b23384740e40fa092c2cbf1befdc0f7153314c79492a1cf4bd

CREATE TABLE authorization_instances (
    instance_key TEXT PRIMARY KEY,
    schema_version BIGINT NOT NULL CHECK (schema_version > 0),
    catalog_version BIGINT NOT NULL CHECK (catalog_version > 0),
    catalog_digest TEXT NOT NULL,
    root_scope_id TEXT NOT NULL,
    active_policy_revision BIGINT NOT NULL CHECK (active_policy_revision > 0),
    next_id BIGINT NOT NULL DEFAULT 0 CHECK (next_id >= 0),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE authorization_scopes (
    instance_key TEXT NOT NULL REFERENCES authorization_instances(instance_key) ON DELETE RESTRICT,
    id TEXT NOT NULL,
    scope_type TEXT NOT NULL,
    parent_id TEXT,
    path TEXT NOT NULL,
    depth INTEGER NOT NULL CHECK (depth >= 0),
    status TEXT NOT NULL CHECK (status IN ('active', 'retired')),
    created_at TIMESTAMPTZ NOT NULL,
    retired_at TIMESTAMPTZ,
    PRIMARY KEY (instance_key, id),
    UNIQUE (instance_key, path),
    FOREIGN KEY (instance_key, parent_id)
        REFERENCES authorization_scopes(instance_key, id) ON DELETE RESTRICT
);

CREATE TABLE authorization_policy_revisions (
    instance_key TEXT NOT NULL REFERENCES authorization_instances(instance_key) ON DELETE RESTRICT,
    revision BIGINT NOT NULL CHECK (revision > 0),
    base_revision BIGINT CHECK (base_revision > 0),
    state TEXT NOT NULL CHECK (state IN ('draft', 'active', 'superseded', 'discarded')),
    created_by_kind TEXT NOT NULL,
    created_by_id TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    activated_at TIMESTAMPTZ,
    PRIMARY KEY (instance_key, revision)
);

CREATE UNIQUE INDEX authorization_one_active_policy
    ON authorization_policy_revisions(instance_key)
    WHERE state = 'active';

CREATE TABLE authorization_policy_scopes (
    instance_key TEXT NOT NULL,
    revision BIGINT NOT NULL,
    scope_id TEXT NOT NULL,
    PRIMARY KEY (instance_key, revision, scope_id),
    FOREIGN KEY (instance_key, revision)
        REFERENCES authorization_policy_revisions(instance_key, revision) ON DELETE RESTRICT,
    FOREIGN KEY (instance_key, scope_id)
        REFERENCES authorization_scopes(instance_key, id) ON DELETE RESTRICT
);

CREATE TABLE authorization_role_definitions (
    instance_key TEXT NOT NULL REFERENCES authorization_instances(instance_key) ON DELETE RESTRICT,
    id TEXT NOT NULL,
    role_key TEXT NOT NULL,
    scope_id TEXT NOT NULL,
    kind TEXT NOT NULL CHECK (kind IN ('builtin', 'custom')),
    protected BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL,
    created_by_kind TEXT,
    created_by_id TEXT,
    retired_at TIMESTAMPTZ,
    PRIMARY KEY (instance_key, id),
    UNIQUE (instance_key, role_key),
    FOREIGN KEY (instance_key, scope_id)
        REFERENCES authorization_scopes(instance_key, id) ON DELETE RESTRICT
);

CREATE TABLE authorization_role_policies (
    instance_key TEXT NOT NULL,
    revision BIGINT NOT NULL,
    role_id TEXT NOT NULL,
    display_name TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('active', 'retired')),
    assignment_sources JSONB NOT NULL CHECK (jsonb_typeof(assignment_sources) = 'array'),
    max_duration_seconds BIGINT NOT NULL DEFAULT 0 CHECK (max_duration_seconds >= 0),
    PRIMARY KEY (instance_key, revision, role_id),
    FOREIGN KEY (instance_key, revision)
        REFERENCES authorization_policy_revisions(instance_key, revision) ON DELETE RESTRICT,
    FOREIGN KEY (instance_key, role_id)
        REFERENCES authorization_role_definitions(instance_key, id) ON DELETE RESTRICT
);

CREATE TABLE authorization_policy_bindings (
    instance_key TEXT NOT NULL,
    revision BIGINT NOT NULL,
    target_kind TEXT NOT NULL CHECK (target_kind IN ('role', 'access_layer')),
    target_key TEXT NOT NULL,
    capability_key TEXT NOT NULL,
    PRIMARY KEY (instance_key, revision, target_kind, target_key, capability_key),
    FOREIGN KEY (instance_key, revision)
        REFERENCES authorization_policy_revisions(instance_key, revision) ON DELETE RESTRICT
);

CREATE TABLE authorization_automatic_rules (
    instance_key TEXT NOT NULL,
    revision BIGINT NOT NULL,
    rule_key TEXT NOT NULL,
    trigger_key TEXT NOT NULL,
    predicate_key TEXT NOT NULL,
    role_id TEXT NOT NULL,
    scope_id TEXT NOT NULL,
    enabled BOOLEAN NOT NULL,
    parameters JSONB NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (instance_key, revision, rule_key),
    FOREIGN KEY (instance_key, revision)
        REFERENCES authorization_policy_revisions(instance_key, revision) ON DELETE RESTRICT,
    FOREIGN KEY (instance_key, role_id)
        REFERENCES authorization_role_definitions(instance_key, id) ON DELETE RESTRICT,
    FOREIGN KEY (instance_key, scope_id)
        REFERENCES authorization_scopes(instance_key, id) ON DELETE RESTRICT
);

CREATE TABLE authorization_groups (
    instance_key TEXT NOT NULL REFERENCES authorization_instances(instance_key) ON DELETE RESTRICT,
    id TEXT NOT NULL,
    scope_id TEXT NOT NULL,
    display_name TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('active', 'retired')),
    created_at TIMESTAMPTZ NOT NULL,
    retired_at TIMESTAMPTZ,
    PRIMARY KEY (instance_key, id),
    FOREIGN KEY (instance_key, scope_id)
        REFERENCES authorization_scopes(instance_key, id) ON DELETE RESTRICT
);

CREATE TABLE authorization_group_members (
    instance_key TEXT NOT NULL,
    group_id TEXT NOT NULL,
    subject_kind TEXT NOT NULL CHECK (subject_kind IN ('user', 'service')),
    subject_id TEXT NOT NULL,
    added_at TIMESTAMPTZ NOT NULL,
    added_by_kind TEXT NOT NULL,
    added_by_id TEXT NOT NULL,
    removed_at TIMESTAMPTZ,
    removed_by_kind TEXT,
    removed_by_id TEXT,
    PRIMARY KEY (instance_key, group_id, subject_kind, subject_id, added_at),
    FOREIGN KEY (instance_key, group_id)
        REFERENCES authorization_groups(instance_key, id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX authorization_active_group_member
    ON authorization_group_members(instance_key, group_id, subject_kind, subject_id)
    WHERE removed_at IS NULL;

CREATE TABLE authorization_grants (
    instance_key TEXT NOT NULL REFERENCES authorization_instances(instance_key) ON DELETE RESTRICT,
    id TEXT NOT NULL,
    target_kind TEXT NOT NULL CHECK (target_kind IN ('user', 'service', 'group')),
    target_id TEXT NOT NULL,
    role_id TEXT NOT NULL,
    scope_id TEXT NOT NULL,
    source TEXT NOT NULL,
    valid_from TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    revoked_by_kind TEXT,
    revoked_by_id TEXT,
    predecessor_id TEXT,
    provenance_type TEXT,
    provenance_id TEXT,
    created_by_kind TEXT,
    created_by_id TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (instance_key, id),
    FOREIGN KEY (instance_key, role_id)
        REFERENCES authorization_role_definitions(instance_key, id) ON DELETE RESTRICT,
    FOREIGN KEY (instance_key, scope_id)
        REFERENCES authorization_scopes(instance_key, id) ON DELETE RESTRICT,
    FOREIGN KEY (instance_key, predecessor_id)
        REFERENCES authorization_grants(instance_key, id) ON DELETE RESTRICT,
    CHECK (expires_at IS NULL OR expires_at > valid_from)
);

CREATE INDEX authorization_grants_lookup
    ON authorization_grants(instance_key, target_kind, target_id, scope_id);

CREATE TABLE authorization_applications (
    instance_key TEXT NOT NULL REFERENCES authorization_instances(instance_key) ON DELETE RESTRICT,
    id TEXT NOT NULL,
    request_group_id TEXT,
    subject_kind TEXT NOT NULL CHECK (subject_kind = 'user'),
    subject_id TEXT NOT NULL,
    role_id TEXT NOT NULL,
    scope_id TEXT NOT NULL,
    reason TEXT NOT NULL,
    state TEXT NOT NULL CHECK (state IN ('pending', 'approved', 'rejected', 'withdrawn', 'expired')),
    grant_id TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    reviewed_at TIMESTAMPTZ,
    reviewed_by_kind TEXT,
    reviewed_by_id TEXT,
    review_reason TEXT,
    idempotency_key TEXT,
    previous_application_id TEXT,
    PRIMARY KEY (instance_key, id),
    FOREIGN KEY (instance_key, role_id)
        REFERENCES authorization_role_definitions(instance_key, id) ON DELETE RESTRICT,
    FOREIGN KEY (instance_key, scope_id)
        REFERENCES authorization_scopes(instance_key, id) ON DELETE RESTRICT,
    FOREIGN KEY (instance_key, grant_id)
        REFERENCES authorization_grants(instance_key, id) ON DELETE RESTRICT,
    FOREIGN KEY (instance_key, previous_application_id)
        REFERENCES authorization_applications(instance_key, id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX authorization_pending_application
    ON authorization_applications(instance_key, subject_kind, subject_id, role_id, scope_id)
    WHERE state = 'pending';

CREATE UNIQUE INDEX authorization_application_idempotency
    ON authorization_applications(instance_key, subject_kind, subject_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL;

CREATE TABLE authorization_invitations (
    instance_key TEXT NOT NULL REFERENCES authorization_instances(instance_key) ON DELETE RESTRICT,
    id TEXT NOT NULL,
    subject_kind TEXT,
    subject_id TEXT,
    normalized_email TEXT,
    role_id TEXT NOT NULL,
    scope_id TEXT NOT NULL,
    token_digest BYTEA NOT NULL,
    state TEXT NOT NULL CHECK (state IN ('pending', 'accepted', 'declined', 'revoked', 'expired')),
    invited_by_kind TEXT NOT NULL,
    invited_by_id TEXT NOT NULL,
    accepted_by_kind TEXT,
    accepted_by_id TEXT,
    grant_id TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    token_rotated_at TIMESTAMPTZ,
    PRIMARY KEY (instance_key, id),
    UNIQUE (instance_key, token_digest),
    FOREIGN KEY (instance_key, role_id)
        REFERENCES authorization_role_definitions(instance_key, id) ON DELETE RESTRICT,
    FOREIGN KEY (instance_key, scope_id)
        REFERENCES authorization_scopes(instance_key, id) ON DELETE RESTRICT,
    FOREIGN KEY (instance_key, grant_id)
        REFERENCES authorization_grants(instance_key, id) ON DELETE RESTRICT,
    CHECK ((subject_id IS NOT NULL) <> (normalized_email IS NOT NULL))
);

CREATE TABLE authorization_inbox_events (
    instance_key TEXT NOT NULL REFERENCES authorization_instances(instance_key) ON DELETE RESTRICT,
    source TEXT NOT NULL,
    event_id TEXT NOT NULL,
    subject_kind TEXT NOT NULL,
    subject_id TEXT NOT NULL,
    policy_revision BIGINT NOT NULL,
    result JSONB NOT NULL,
    handled_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (instance_key, source, event_id),
    FOREIGN KEY (instance_key, policy_revision)
        REFERENCES authorization_policy_revisions(instance_key, revision) ON DELETE RESTRICT
);

CREATE TABLE authorization_audit_events (
    instance_key TEXT NOT NULL REFERENCES authorization_instances(instance_key) ON DELETE RESTRICT,
    id TEXT NOT NULL,
    action TEXT NOT NULL,
    actor_kind TEXT,
    actor_id TEXT,
    subject_kind TEXT,
    subject_id TEXT,
    role_key TEXT,
    scope_id TEXT,
    policy_revision BIGINT NOT NULL,
    correlation_id TEXT,
    before_digest TEXT,
    after_digest TEXT,
    detail JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (instance_key, id)
);

CREATE INDEX authorization_audit_search
    ON authorization_audit_events(instance_key, occurred_at DESC, action);
CREATE INDEX authorization_audit_correlation
    ON authorization_audit_events(instance_key, correlation_id)
    WHERE correlation_id IS NOT NULL;

CREATE TABLE authorization_decision_events (
    instance_key TEXT NOT NULL REFERENCES authorization_instances(instance_key) ON DELETE RESTRICT,
    decision_id TEXT NOT NULL,
    subject_kind TEXT NOT NULL,
    subject_id TEXT,
    capability_key TEXT NOT NULL,
    scope_id TEXT NOT NULL,
    resource_type TEXT,
    resource_id TEXT,
    resource_revision TEXT,
    allowed BOOLEAN NOT NULL,
    reason TEXT NOT NULL,
    constraint_key TEXT,
    policy_revision BIGINT NOT NULL,
    sources JSONB NOT NULL,
    correlation_id TEXT,
    occurred_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (instance_key, decision_id)
);

CREATE INDEX authorization_decisions_search
    ON authorization_decision_events(instance_key, occurred_at DESC, allowed, capability_key);
CREATE INDEX authorization_decisions_correlation
    ON authorization_decision_events(instance_key, correlation_id)
    WHERE correlation_id IS NOT NULL;

-- Derived execution data. It may be deleted and rebuilt solely from the
-- preceding domain-truth tables.
CREATE TABLE authorization_projection_rules (
    instance_key TEXT NOT NULL REFERENCES authorization_instances(instance_key) ON DELETE CASCADE,
    policy_revision BIGINT NOT NULL,
    rule_kind TEXT NOT NULL CHECK (rule_kind IN ('permission', 'membership', 'access_layer')),
    subject_key TEXT NOT NULL,
    role_key TEXT NOT NULL,
    capability_key TEXT NOT NULL DEFAULT '',
    scope_id TEXT NOT NULL,
    provenance JSONB NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (
        instance_key, policy_revision, rule_kind, subject_key,
        role_key, capability_key, scope_id
    )
);

