-- Code generated by foundation audit; DO NOT EDIT.
-- audit-schema-version: 1
-- audit-schema-digest: 924781bfe8b76a14c86018b258de1959faec5cafc839edd9af7c8718d330e302

DROP TABLE IF EXISTS audit_mirror_outbox;
DROP TABLE IF EXISTS audit_retention_receipts;
DROP TABLE IF EXISTS audit_legal_holds;
DROP TABLE IF EXISTS audit_event_receipts;
DROP TABLE IF EXISTS audit_events;
DROP TABLE IF EXISTS audit_action_definitions;
DROP TABLE IF EXISTS audit_instances;

