-- Code generated by foundation audit; DO NOT EDIT.
-- audit-schema-version: 1
-- audit-schema-digest: 924781bfe8b76a14c86018b258de1959faec5cafc839edd9af7c8718d330e302

CREATE TABLE audit_instances (
    instance_key TEXT PRIMARY KEY,
    schema_version INTEGER NOT NULL,
    consumer TEXT NOT NULL,
    definition_version BIGINT NOT NULL,
    definition_digest TEXT NOT NULL,
    head_sequence BIGINT NOT NULL DEFAULT 0,
    head_digest TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE audit_action_definitions (
    instance_key TEXT NOT NULL REFERENCES audit_instances(instance_key) ON DELETE RESTRICT,
    action_name TEXT NOT NULL,
    action_version INTEGER NOT NULL,
    definition_digest TEXT NOT NULL,
    definition JSONB NOT NULL,
    registered_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (instance_key, action_name, action_version)
);

CREATE TABLE audit_events (
    instance_key TEXT NOT NULL REFERENCES audit_instances(instance_key) ON DELETE RESTRICT,
    id TEXT NOT NULL,
    sequence BIGINT NOT NULL,
    envelope_version INTEGER NOT NULL,
    source JSONB NOT NULL,
    action_name TEXT NOT NULL,
    action_version INTEGER NOT NULL,
    category TEXT NOT NULL,
    actor_kind TEXT NOT NULL,
    actor_id TEXT,
    target_type TEXT NOT NULL,
    target_id TEXT NOT NULL,
    outcome_kind TEXT NOT NULL,
    outcome_reason TEXT,
    correlation JSONB NOT NULL,
    evidence JSONB NOT NULL,
    retention_class TEXT NOT NULL,
    definition_digest TEXT NOT NULL,
    fingerprint TEXT NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL,
    previous_digest TEXT,
    digest TEXT NOT NULL,
    PRIMARY KEY (instance_key, sequence),
    UNIQUE (instance_key, id),
    FOREIGN KEY (instance_key, action_name, action_version)
        REFERENCES audit_action_definitions(instance_key, action_name, action_version) ON DELETE RESTRICT
);

CREATE TABLE audit_event_receipts (
    instance_key TEXT NOT NULL REFERENCES audit_instances(instance_key) ON DELETE RESTRICT,
    id TEXT NOT NULL,
    fingerprint TEXT NOT NULL,
    sequence BIGINT NOT NULL,
    event_digest TEXT NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL,
    purged_at TIMESTAMPTZ,
    PRIMARY KEY (instance_key, id),
    UNIQUE (instance_key, sequence)
);

CREATE INDEX audit_events_action_search
    ON audit_events(instance_key, action_name, action_version, sequence DESC);
CREATE INDEX audit_events_actor_search
    ON audit_events(instance_key, actor_kind, actor_id, sequence DESC);
CREATE INDEX audit_events_target_search
    ON audit_events(instance_key, target_type, target_id, sequence DESC);
CREATE INDEX audit_events_outcome_search
    ON audit_events(instance_key, outcome_kind, sequence DESC);
CREATE INDEX audit_events_occurred_search
    ON audit_events(instance_key, occurred_at DESC, sequence DESC);
CREATE INDEX audit_events_correlation_search
    ON audit_events(instance_key, ((correlation->>'requestId')), sequence DESC)
    WHERE correlation->>'requestId' IS NOT NULL;
CREATE INDEX audit_events_trace_search
    ON audit_events(instance_key, ((correlation->>'traceId')), sequence DESC)
    WHERE correlation->>'traceId' IS NOT NULL;

CREATE TABLE audit_legal_holds (
    instance_key TEXT NOT NULL REFERENCES audit_instances(instance_key) ON DELETE RESTRICT,
    id TEXT NOT NULL,
    selection JSONB NOT NULL,
    reason TEXT NOT NULL,
    placed_by JSONB NOT NULL,
    placed_at TIMESTAMPTZ NOT NULL,
    release_reason TEXT,
    released_by JSONB,
    released_at TIMESTAMPTZ,
    PRIMARY KEY (instance_key, id)
);

CREATE TABLE audit_retention_receipts (
    instance_key TEXT NOT NULL REFERENCES audit_instances(instance_key) ON DELETE RESTRICT,
    id TEXT NOT NULL,
    as_of TIMESTAMPTZ NOT NULL,
    deleted_count BIGINT NOT NULL,
    deleted_ranges JSONB NOT NULL,
    archive_manifest JSONB,
    created_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (instance_key, id)
);

CREATE TABLE audit_mirror_outbox (
    instance_key TEXT NOT NULL,
    sequence BIGINT NOT NULL,
    event JSONB NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMPTZ NOT NULL,
    delivered_at TIMESTAMPTZ,
    last_error_code TEXT,
    PRIMARY KEY (instance_key, sequence),
    FOREIGN KEY (instance_key, sequence)
        REFERENCES audit_events(instance_key, sequence) ON DELETE CASCADE
);

