// Code generated by foundation httpcontract; DO NOT EDIT.

package reserr

import (
	"sort"

	"github.com/yueli-official/foundation/go/problem"
)

const (
	CodeAssetNotFound            = "resource.asset_not_found"
	CodeAuthorizationUnavailable = "resource.authorization_unavailable"
	CodeForbidden                = "resource.forbidden"
	CodeInvalidInput             = "resource.invalid_input"
	CodeInvalidState             = "resource.invalid_state"
	CodeInvalidType              = "resource.invalid_type"
	CodeNotFound                 = "resource.not_found"
	CodePreconditionRequired     = "resource.site_profile_precondition_required"
	CodeRevisionConflict         = "resource.site_profile_revision_conflict"
	CodeSlugTaken                = "resource.slug_taken"
	CodeUpstreamFailed           = "resource.upstream_failed"
)

var descriptors = map[string]problem.Descriptor{
	CodeAssetNotFound:            descriptor(CodeAssetNotFound, 404),
	CodeAuthorizationUnavailable: descriptor(CodeAuthorizationUnavailable, 503),
	CodeForbidden:                descriptor(CodeForbidden, 403),
	CodeInvalidInput:             descriptor(CodeInvalidInput, 400),
	CodeInvalidState:             descriptor(CodeInvalidState, 409),
	CodeInvalidType:              descriptor(CodeInvalidType, 400),
	CodeNotFound:                 descriptor(CodeNotFound, 404),
	CodePreconditionRequired:     descriptor(CodePreconditionRequired, 428),
	CodeRevisionConflict:         descriptor(CodeRevisionConflict, 412),
	CodeSlugTaken:                descriptor(CodeSlugTaken, 409),
	CodeUpstreamFailed:           descriptor(CodeUpstreamFailed, 502),
}

func descriptor(code string, status int) problem.Descriptor {
	return problem.MustDescriptor(problem.MustKind(code, status), "https://errors.yueli.dev/problems/"+code)
}

func DescriptorForCode(code string) (problem.Descriptor, bool) {
	value, ok := descriptors[code]
	return value, ok
}

type CatalogEntry struct {
	Code   string `json:"code"`
	Status int    `json:"status"`
}

func Catalog() []CatalogEntry {
	result := make([]CatalogEntry, 0, len(descriptors))
	for code, value := range descriptors {
		result = append(result, CatalogEntry{Code: code, Status: value.Kind().Status()})
	}
	sort.Slice(result, func(i, j int) bool { return result[i].Code < result[j].Code })
	return result
}
